<!DOCTYPE html>
<html>
<head>
    <meta charset="iso-8859-9 Türkçe" />
    <title>js1392.html: JS hata yakalama/fýrlatma try-catch-finally/throw örneði.</title>
    <style>
        body {background-color:OliveDrab; color: Maroon; font-size:20px;}
        input {background-color:Navy; color:orange;}
        button {background-color: red; color: yellow; font-size:15px;}
        #göster {color:Yellow; font-size:18px; margin-top:2em; text-align:ccenter;}
    </style>
    <script>
        function fonk1() {document.getElementById ("göster").innerHTML ="";}
        function fonk2() {document.getElementById ("mesaj").innerHTML ="";}
    </script>
</head>
<body>
    <input type="button" value="reload() ile Yenile" onClick="window.location.reload();"><br/>
    <input type="button" value="Sil Açýklama" onClick="fonk1()">
    <input type="button" value="Sil Veri Giriþi" onClick="fonk2()">
    <h4>HATALAR-2</h4>
    <p id="göster">Paragraf</p>

    <script>
        function hata1() {
            try {naMevcutDeðiþken;}catch {return "Bu aþamada bir hata yakalandý!..";}
            return "Hata yakalanmadý.";
        } // fonk sonu...

        function hata2() {
            try {naMevcutDeðiþken;
            }catch (istisna) {return `<br/>HATA (adý=${istisna.name}<br/>mesajý=${istisna.message}<br/>ve yýðýný=${istisna.stack})`;}
            return "Hata yakalanmadý.";
        } // fonk sonu...

        function hata3 (yaþ) {
            try {if (yaþ < 0) throw new Error ("Negatif yaþ olmaz!");
            }catch (ist) {return `<br/>HATA (adý=${ist.name}<br/>mesajý=${ist.message}<br/>ve yýðýný=${ist.stack})`;}
            return "Hata yakalanmadý.";
        } // fonk sonu...

        function hata4 (yaþ) {
            try {if (yaþ > 64) throw new Error ("TCDD ile %50 indirimli seyahat edebilirsiniz.");
                else if (yaþ > 59) throw new Error ("TCDD ile %20 indirimli seyahat edebilirsiniz.");
                else if (yaþ > 17) throw new SyntaxError ("Reþitler oy kullanabilir.");
                else if (yaþ > 0) throw new SyntaxError ("Çocuklar henüz oy kullanamaz.");
                else throw new ReferenceError ("Henüz doðmamýþsýnýz!");
            }catch (ist) {if (ist.name == "ReferenceError") throw ist;
                else return `<br/>HATA (adý=${ist.name}<br/>mesajý=${ist.message}<br/>ve yýðýný=${ist.stack})`;}
            return "Hata yakalanmadý.";
        } // fonk sonu...
        try {hata4 ();}catch (ist) {alert ("Harici bir rethrow/tekrarfýrlatma yakalandý: " + ist);}

        function hata5() {
            function fib (n) {return n <= 1 ? n : fib (n - 1) + fib (n - 2);
            } // fonk sonu...
            let ilk=0, son=0, süre, sonuç;
            try {let sayý = +prompt ("Pozitif bir tamsayý girin?", 35)
                if (sayý == NaN || sayý < 0 || Math.trunc (sayý) != sayý) throw new Error ("NaN, negatif veya küsüratlý sayý giremezsiniz.");
                ilk = Date.now(); sonuç = fib (sayý); son = Date.now();
            }catch (ist) {alert (ist); sonuç = 0;
            }finally {süre = son - ilk;}
            alert (sonuç || "Hata fýrlatýldý");
            alert (`Ýþlem süresi = ${süre} ms`);
        } // fonk sonu...

        window.onerror = function (mesaj, yurel, satýr, sütun, hata) {
            document.getElementById ("göster").innerHTML +=
            "<br>Hata: " + hata + "<br>Mesaj: " + mesaj + "<br>Satýr no: " + satýr + "<br>Sütun no: " + sütun + "<br>Yurel: " + yurel;
        }; // win.. sonu...

        document.getElementById ("göster").innerHTML =
            "1) JS kodlama hatalarý try-catch'le yakalanmaz, tarayýcý yorumlama esnasýnda \
            susar, hatayý F12 debugger/hataayýklayýcý'da görebiliriz. try-catch'le yakalanabilen \
            hatalar kodlama/syntax/sözdizim deðil, istisnalar da denilen çalýþma zamaný \
            hatalarýdýr ve hata bu blok içinde oluþurken yakalanmalýdýr: " + hata1() +
            "<br/>2) Hata yakalandýðýnda catch(hata)'nýn name/ad, message/mesaj ve \
            stack/yýðýn olmak üzere üç geridönüþü vardýr: " + hata2() +
            "<br/>3) Hata yakalandýðýnda kendi hata nesnemizi de throw/fýrlatabiliriz \
            (new Error, new SyntaxError, new ReferenceError(mesaj)): " + hata3 (-20) +
            "<br/>4) Bilinen ve throw'la yakalanan bir hata haricindeki tüm hatalar rethrow\
            /tekrarfýrlat'la dýþardan yakalanabilir: " + hata4 (67) +
            "<br/>5) try-catch-finally'da finally her halükarda iþletilir: " + hata5() +
            "<br/>6) catch'siz try-finally da kullanýlabilir." +
            "<br/>7) try-catch dýþý her türlü çalýþma zamaný hatalarýný yakalamak için \
            genel 'window.onerror' kullanýlabilir: ";

        function oku() {namevcut();}
        oku();
    </script>
</body>
</html>